#!/bin/sh
#
#  Notes
#   - This script has been tested to work with RHEL & CentOS
#   - This script must be run as root
#
#  Author
#  Marc S. Brooks <devel@mbrooks.info>
#

BASE_DIR=/usr/local/drupal+
LOCKFILE=/var/lock/subsys/drupal+php-fpm

. /etc/init.d/functions

if [ ! -d $BASE_DIR ]; then
    exit 1
fi

start() {
    action $"Starting php-fpm process:" daemon $BASE_DIR/bin/php-fpm

    if [ $? -eq 0 ]; then
        touch $LOCKFILE
    fi
}

stop() {
    action $"Stopping php-fpm process:" killproc php-fpm

    if [ $? -eq 0 ]; then
        rm -f $LOCKFILE
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)

    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
